
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import javax.swing.JOptionPane;

/**
 *
 * @author EQUIPO: Pablo Manrique, Irving Cisneros, Andrés Molina, Emiliano Ruiz, Marco, Pahola Munive.
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        setSize(670,230);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        imagUser = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblUsuario = new javax.swing.JLabel();
        lblContraseña = new javax.swing.JLabel();
        cUsuario = new javax.swing.JTextField();
        cPass = new javax.swing.JPasswordField();
        SalirHPH = new javax.swing.JButton();
        IngresarHPH = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ImagMain/logoHPH.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 90));

        imagUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ImagMain/useeer.png"))); // NOI18N
        getContentPane().add(imagUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 100, 100));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 20, 80));

        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");
        getContentPane().add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, -1));

        lblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        lblContraseña.setText("Contraseña:");
        getContentPane().add(lblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, -1, -1));

        cUsuario.setForeground(new java.awt.Color(153, 153, 153));
        cUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cUsuarioActionPerformed(evt);
            }
        });
        cUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cUsuarioKeyTyped(evt);
            }
        });
        getContentPane().add(cUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 220, -1));
        getContentPane().add(cPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 200, -1));

        SalirHPH.setText("Salir");
        SalirHPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirHPHActionPerformed(evt);
            }
        });
        getContentPane().add(SalirHPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 190, -1, -1));

        IngresarHPH.setText("Ingresar");
        IngresarHPH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IngresarHPHActionPerformed(evt);
            }
        });
        getContentPane().add(IngresarHPH, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 670, 10));

        jLabel3.setFont(new java.awt.Font("GulimChe", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("NOTA: Ingrese nombre de usuario");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/ImagMain/fondo.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 230));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirHPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirHPHActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        
    }//GEN-LAST:event_SalirHPHActionPerformed

    private void IngresarHPHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IngresarHPHActionPerformed
       
        String us = cUsuario.getText();
        String con = cPass.getText();
        
        String pass = new String(cPass.getPassword());
                
        /*if((us.isEmpty())||(pass.isEmpty())){
            JOptionPane.showMessageDialog(null,
                    "Ingrese ambos campos.");            
        }*/
        
        //else{
        
            if(cUsuario.getText().equals("") || (cPass.getText().equals(""))){
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Ingrese en ambos campos.",
                    "AVISO",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE
                    );
            
        }
        else{
                if(cUsuario.getText().equals(us) && pass.equals(con)){
                JOptionPane.showMessageDialog(
                    MainFrame.this,
                    "B I E N V E N I D O",
                    "Acceso concedido",
                    JOptionPane.INFORMATION_MESSAGE);
                
                Trabajadores trab = new Trabajadores();
                trab.setVisible(true);
                trab.pack();
                trab.setLocationRelativeTo(null);
                
                this.setVisible(false); //funciona como un dispose()
                }
                
                else
                    JOptionPane.showMessageDialog(
                    MainFrame.this,
                    "INCORRECTO, vuelva a intentar.",
                    "Acceso denegado",
                    JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_IngresarHPHActionPerformed
}
    
    private void cUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cUsuarioKeyTyped
        // TODO add your handling code here:
        char user = evt.getKeyChar();
        if((user<'a' || user>'z') && (user<'A' || user>'Z') && (user<' ' || user>' '))
            evt.consume();
    }//GEN-LAST:event_cUsuarioKeyTyped

    private void cUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IngresarHPH;
    private javax.swing.JButton SalirHPH;
    private javax.swing.JPasswordField cPass;
    private javax.swing.JTextField cUsuario;
    private javax.swing.JLabel imagUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContraseña;
    private javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
